# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'daily'
      # Set to minimise the number of chromatic runs.
      rebase-strategy: "disabled"
    - package-ecosystem: 'npm'
      directory: '/apps-rendering'
      schedule:
          interval: 'daily'
      labels:
        - "AR Dependency"
      rebase-strategy: "disabled"
    - package-ecosystem: "npm"
      directory: "/dotcom-rendering"
      schedule:
        interval: "daily"
      labels:
        - "DCR Dependency"
      open-pull-requests-limit: 10
      rebase-strategy: "disabled"
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'daily'
      rebase-strategy: "disabled"
