name: Chromatic 👓
on: push

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: guardian/actions-setup-node@main

      # Cache npm dependencies using https://github.com/bahmutov/npm-install
      # Root yarn installs all workspaces (root, common, dotcom)
      - uses: bahmutov/npm-install@v1

      # Install packages for apps-rendering project
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: apps-rendering

      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          autoAcceptChanges: main
