name: DCR Run Lighthouse CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - "apps-rendering/**"
  pull_request:
    #  If/when we compare results to `main`, we should also run on 'reopened'
    types: [opened, synchronize]

jobs:
  lhci:
    name: DCR Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Node
        uses: guardian/actions-setup-node@main
      # Make sure we install dependencies in the root directory
      - uses: bahmutov/npm-install@v1
      - run: make build
        working-directory: dotcom-rendering
      - name: Install and run Lighthouse CI
        working-directory: dotcom-rendering
        env:
          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
        run: |
          npm install -g puppeteer-core@2.1.0 @lhci/cli@0.8.2
          lhci autorun

      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.21.0

      - name: Surface Lighthouse Results
        run: deno run --no-check --allow-net=api.github.com --allow-env="GITHUB_TOKEN","GITHUB_EVENT_PATH" --allow-read scripts/deno/surface-lighthouse-results.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
